# https://modoocode.com/311 참고해서 정리해보기


# Makefile로 만들어진 libraray 사용법은 하기를 참고해보자
# https://velog.io/@hidaehyunlee/%EC%99%B8%EB%B6%80-%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC-GCC%EB%A1%9C-%EC%BB%B4%ED%8C%8C%EC%9D%BC-%ED%95%98%EA%B8%B0
